spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_service?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
