spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food-service?useSSL=false&serverTimezone=UTC
    username: "{cipher}a0e18b54343303ef9b8e7319c540c7a237b27faf6e69b9d472d567736b08b987"
    password: "{cipher}a0e18b54343303ef9b8e7319c540c7a237b27faf6e69b9d472d567736b08b987"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
